### ISSUE TITLE
env doesn't honour the case format but transform the variables to capital case.

### ISSUE THREAD

**Issue by v1v** [avaly/gcp-secret-manager-buildkite-plugin#9]
```yaml
steps:
  - command: 'echo \$SECRET_VAR'
    plugins:
      - avaly/gcp-secret-manager#v1.2.0:
          credentials_file: /etc/gcloud-credentials.json
          env:
            my_SECRET: my-secret-name
            OTHER_SECRET_VAR: my-other-secret-name
```

I'd expect the variable name `my_SECRET`, but it is created with the `MY_SECRET` name, hence tools such as `terraform` might complain as they have quite an opinionated way of passing parameters.
